
import 'package:flutterweather/features/data/model/NearsetArea.dart';
import 'package:flutterweather/features/data/model/Weather.dart';
import 'package:flutterweather/features/data/model/currentcondition.dart';
import 'package:flutterweather/features/data/model/request.dart';


// class Autogenerated {
//   List<CurrentCondition>? currentCondition;
//   List<NearestArea>? nearestArea;
//   List<Request>? request;
//   List<Weather>? weather;

//   Autogenerated(
//       {this.currentCondition, this.nearestArea, this.request, this.weather});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     if (json['current_condition'] != null) {
//       currentCondition = <CurrentCondition>[];
//       json['current_condition'].forEach((v) {
//         currentCondition!.add(new CurrentCondition.fromJson(v));
//       });
//     }
//     if (json['nearest_area'] != null) {
//       nearestArea = <NearestArea>[];
//       json['nearest_area'].forEach((v) {
//         nearestArea!.add(new NearestArea.fromJson(v));
//       });
//     }
//     if (json['request'] != null) {
//       request = <Request>[];
//       json['request'].forEach((v) {
//         request!.add(new Request.fromJson(v));
//       });
//     }
//     if (json['weather'] != null) {
//       weather = <Weather>[];
//       json['weather'].forEach((v) {
//         weather!.add(new Weather.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.currentCondition != null) {
//       data['current_condition'] =
//           this.currentCondition!.map((v) => v.toJson()).toList();
//     }
//     if (this.nearestArea != null) {
//       data['nearest_area'] = this.nearestArea!.map((v) => v.toJson()).toList();
//     }
//     if (this.request != null) {
//       data['request'] = this.request!.map((v) => v.toJson()).toList();
//     }
//     if (this.weather != null) {
//       data['weather'] = this.weather!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class Autogenerated {
//   List<CurrentCondition>? currentCondition;
//   List<NearestArea>? nearestArea;
//   List<Request>? request;
//   List<WeatherModel>? weather;

//   Autogenerated({this.currentCondition, this.nearestArea, this.request, this.weather, List<WeatherModel>? WeatherModel, List<WeatherModel>? Weather,});

//   factory Autogenerated.fromJson(Map<String, dynamic> json) {
//     return Autogenerated(
//       currentCondition: json['current_condition'] != null
//           ? (json['current_condition'] as List).map((v) => CurrentCondition.fromJson(v)).toList()
//           : null,
//       nearestArea: json['nearest_area'] != null
//           ? (json['nearest_area'] as List).map((v) => NearestArea.fromJson(v)).toList()
//           : null,
//       request: json['request'] != null
//           ? (json['request'] as List).map((v) => Request.fromJson(v)).toList()
//           : null,
//       Weather: json['weather'] != null
//           ? (json['weather'] as List).map((v) => WeatherModel.fromJson(v)).toList()
//           : null,
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return {
//       if (currentCondition != null)
//         'current_condition': currentCondition!.map((v) => v.toJson()).toList(),
//       if (nearestArea != null)
//         'nearest_area': nearestArea!.map((v) => v.toJson()).toList(),
//       if (request != null)
//         'request': request!.map((v) => v.toJson()).toList(),
//       if (Weather != null)
//         'weather': WeatherModel!.map((v) => v.toJson()).toList(),
//     };
//   }
// }

class Autogenerated {
  List<CurrentCondition>? currentCondition;
  List<NearestArea>? nearestArea;
  List<Request>? request;
  List<WeatherModel>? weather;

  Autogenerated({this.currentCondition, this.nearestArea, this.request, this.weather});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      currentCondition: (json['current_condition'] as List?)
          ?.map((v) => CurrentCondition.fromJson(v))
          .toList(),
      nearestArea: (json['nearest_area'] as List?)
          ?.map((v) => NearestArea.fromJson(v))
          .toList(),
      request: (json['request'] as List?)
          ?.map((v) => Request.fromJson(v))
          .toList(),
      weather: (json['weather'] as List?)
          ?.map((v) => WeatherModel.fromJson(v))
          .toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'current_condition': currentCondition?.map((v) => v.toJson()).toList(),
      'nearest_area': nearestArea?.map((v) => v.toJson()).toList(),
      'request': request?.map((v) => v.toJson()).toList(),
      'weather': weather?.map((v) => v.toJson()).toList(),
    };
  }
}
