// features/domain/repositories/weather_repository.dart
import '../entities/weather.dart';
import '../../data/model/autogenerated.dart';

abstract class WeatherRepository {
  Future<Autogenerated> fetchWeather([String? location]);
}