// features/data/repositories/weather_repository_impl.dart

import 'package:flutterweather/features/data/datasource/weather_remote.dart';
import 'package:flutterweather/features/domain/repository/repo.dart';

import '../model/autogenerated.dart';

// class WeatherRepositoryImpl implements WeatherRepository {
//   final WeatherRemoteDataSource remoteDataSource;

//   WeatherRepositoryImpl(this.remoteDataSource);

//   @override
//   Future<Autogenerated> fetchWeather() {
//     return remoteDataSource.getWeather();
//   }
// }
class WeatherRepositoryImpl implements WeatherRepository {
  final WeatherRemoteDataSource remoteDataSource;

  WeatherRepositoryImpl(this.remoteDataSource);

  @override
  Future<Autogenerated> fetchWeather([String? location]) async {
    final data = await remoteDataSource.getWeather(location);
    return data;
  }
}