import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../Model/mealto.dart';

// Provider
final apiServiceProvider = Provider<ApiService>((ref) => ApiService());

class ApiService {
  Future<Autogenerated> fetchData(String query) async {
    var url = Uri.https(
      'www.themealdb.com',
      '/api/json/v1/1/search.php',
      {'s': query},
    );

    var response = await http.get(url);
    if (response.statusCode == 200) {
      return Autogenerated.fromJson(jsonDecode(response.body));
    } else {
      throw Exception('Failed to load meals');
    }
  }
}
