import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../Data/Model/mealto.dart';
import '../../Domain/entitie/meal_entity.dart';
import '../../Domain/repositry/meal_repo.dart';
import '../datasource/apiservice.dart';

final mealRepoImplProvider = Provider<MealRepo>((ref) {
  final apiService = ref.watch(apiServiceProvider);
  return MealRepoImpl(apiService);
});

class MealRepoImpl implements MealRepo {
  final ApiService apiService;

  MealRepoImpl(this.apiService);

  @override
  Future<List<MealEntity>> getMealByName(String name) async {
    final autogenerated = await apiService.fetchData(name);
    if (autogenerated.meals == null) {
      return [];
    }
    return autogenerated.meals!
        .map((meal) => MealEntity(
              idMeal: meal.idMeal ?? '',
              strMeal: meal.strMeal ?? '',
              strCategory: meal.strCategory ?? '',
              strArea: meal.strArea ?? '',
              strInstructions: meal.strInstructions ?? '',
              strMealThumb: meal.strMealThumb ?? '',
            ))
        .toList();
  }
}
