// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQ95uXNBAYj3ANJ8oOemH8LwYz8kAYEk',
    appId: '1:354903335212:web:0fe3daa2b07107bd8b8c89',
    messagingSenderId: '354903335212',
    projectId: 'weatherapp-66e7b',
    authDomain: 'weatherapp-66e7b.firebaseapp.com',
    storageBucket: 'weatherapp-66e7b.firebasestorage.app',
    measurementId: 'G-GGTH14P4W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC193iNv41h_pUgiJ3qxBFs4XRfEF9gZd4',
    appId: '1:387409165601:android:26dd3a474bf81d5f49d260',
    messagingSenderId: '387409165601',
    projectId: 'weatherapp-66e7b',
    storageBucket: 'weatherapp-66e7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQ95uXNBAYj3ANJ8oOemH8LwYz8kAYEk',
    appId: '1:354903335212:ios:0a2aef6ae028c2e98b8c89',
    messagingSenderId: '354903335212',
    projectId: 'weatherapp-66e7b',
    storageBucket: 'weatherapp-66e7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterweather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKQ95uXNBAYj3ANJ8oOemH8LwYz8kAYEk',
    appId: '1:354903335212:ios:0a2aef6ae028c2e98b8c89',
    messagingSenderId: '354903335212',
    projectId: 'weatherapp-66e7b',
    storageBucket: 'weatherapp-66e7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterweather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQ95uXNBAYj3ANJ8oOemH8LwYz8kAYEk',
    appId: '1:354903335212:web:158ff51bad640a908b8c89',
    messagingSenderId: '354903335212',
    projectId: 'weatherapp-66e7b',
    authDomain: 'weatherapp-66e7b.firebaseapp.com',
    storageBucket: 'weatherapp-66e7b.firebasestorage.app',
    measurementId: 'G-JKMXM54GVS',
  );
}
