// features/data/datasources/weather_remote_data_source.dart
import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../model/autogenerated.dart';

class WeatherRemoteDataSource {
  Future<Autogenerated> getWeather([String? location]) async {
    // اكثر من منطقةAPI supports location query: wttr.in/Amman?format=j1 or wttr.in/London?format=j1
    String urlString = 'https://wttr.in/?format=j1';
    if (location != null && location.isNotEmpty) {
      urlString = 'https://wttr.in/${Uri.encodeComponent(location)}?format=j1';
    }
    
    try {
      final url = Uri.parse(urlString);
      debugPrint('🌤️ WeatherRemote: Fetching weather from ${url.toString()}');
      
      // Add proper headers to avoid 403 errors
      final headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'User-Agent': 'Mozilla/5.0 (compatible; FlutterApp/1.0)',
      };
      
      final response = await http.get(url, headers: headers).timeout(
        const Duration(seconds: 15),
        onTimeout: () {
          debugPrint('⏱️ WeatherRemote: Request timeout');
          throw Exception('Request timeout: Unable to fetch weather data. Please check your internet connection.');
        },
      );
      
      debugPrint('📡 WeatherRemote: Response status: ${response.statusCode}');

      if (response.statusCode == 200) {
        if (response.body.isEmpty) {
          throw Exception("Empty response from API");
        }
        
        try {
          final jsonData = json.decode(response.body);
          debugPrint('✅ WeatherRemote: Successfully parsed weather data');
          return Autogenerated.fromJson(jsonData);
        } on FormatException catch (e) {
          debugPrint('❌ WeatherRemote: JSON parsing error - ${e.toString()}');
          throw Exception('Invalid JSON response: ${e.toString()}');
        }
      } else if (response.statusCode == 403) {
        debugPrint('❌ WeatherRemote: 403 Forbidden - API access denied');
        throw Exception('Weather API access denied. Please try again later.');
      } else {
        debugPrint('❌ WeatherRemote: HTTP error - Status code ${response.statusCode}');
        throw Exception('Failed to load weather: Status code ${response.statusCode}');
      }
    } on SocketException catch (e) {
      debugPrint('❌ WeatherRemote: SocketException - ${e.toString()}');
      throw Exception('No internet connection. Please check your network.');
    } catch (e) {
      debugPrint('❌ WeatherRemote: Unexpected error - ${e.toString()}');
      if (e is Exception) {
        rethrow;
      }
      throw Exception('Failed to load weather: ${e.toString()}');
    }
  }
}