// features/data/datasources/weather_remote_data_source.dart
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../model/autogenerated.dart';

 class WeatherRemoteDataSource {
  Future<Autogenerated> getWeather([String? location]) async {
    // اكثر من منطقةAPI supports location query: wttr.in/Amman?format=j1 or wttr.in/London?format=j1
    String urlString = 'https://wttr.in/?format=j1';
    if (location != null && location.isNotEmpty) {
      urlString = 'https://wttr.in/${Uri.encodeComponent(location)}?format=j1';
    }
    
    final url = Uri.parse(urlString);
    final response = await http.get(url).timeout(Duration(seconds: 10));
    if(response.body.isEmpty) throw Exception("Empty response from API");

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load weather');
    }
  }
 }