// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGADZyRm7VgSC6FRxaXteEod6QRt7dEjA',
    appId: '1:643400216720:web:8a4b7fc597386859e26815',
    messagingSenderId: '643400216720',
    projectId: 'meal-50068',
    authDomain: 'meal-50068.firebaseapp.com',
    storageBucket: 'meal-50068.firebasestorage.app',
    measurementId: 'G-MD33YBYB7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcyWYhU4JNwW7PuIczWXumj8LZWXRcno',
    appId: '1:643400216720:android:ea8e52389cd14594e26815',
    messagingSenderId: '643400216720',
    projectId: 'meal-50068',
    storageBucket: 'meal-50068.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuREWIC5ye1zTiBQUOcdefUksJG-8UIbI',
    appId: '1:643400216720:ios:9862a765e3509778e26815',
    messagingSenderId: '643400216720',
    projectId: 'meal-50068',
    storageBucket: 'meal-50068.firebasestorage.app',
    iosClientId: '643400216720-uf3h8pa683lq18frta53ej3cig68j7me.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuREWIC5ye1zTiBQUOcdefUksJG-8UIbI',
    appId: '1:643400216720:ios:9862a765e3509778e26815',
    messagingSenderId: '643400216720',
    projectId: 'meal-50068',
    storageBucket: 'meal-50068.firebasestorage.app',
    iosClientId: '643400216720-uf3h8pa683lq18frta53ej3cig68j7me.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGADZyRm7VgSC6FRxaXteEod6QRt7dEjA',
    appId: '1:643400216720:web:d1c0cd00b16fec6ee26815',
    messagingSenderId: '643400216720',
    projectId: 'meal-50068',
    authDomain: 'meal-50068.firebaseapp.com',
    storageBucket: 'meal-50068.firebasestorage.app',
    measurementId: 'G-N0CC9CZL89',
  );
}
