import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterweather/features/data/model/autogenerated.dart';
import 'package:flutterweather/features/presentation/bloc/weatherbloc.dart';
import 'package:flutterweather/features/presentation/bloc/weatherevent.dart';
import 'package:flutterweather/features/presentation/bloc/weatherstate.dart';
import 'package:flutterweather/features/presentation/bloc/auth/auth_bloc.dart';
import 'package:flutterweather/features/presentation/bloc/auth/auth_event.dart';
import 'package:flutterweather/injectionDependancy.dart';
import 'package:flutterweather/features/data/datasource/firebase_messaging_service.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:skeletonizer/skeletonizer.dart';



class WeatherPage extends StatefulWidget {
  const WeatherPage({super.key});

  @override
  State<WeatherPage> createState() => _WeatherPageState();
}

class _WeatherPageState extends State<WeatherPage> {
  final TextEditingController _searchController = TextEditingController();
  final TextEditingController _cityController = TextEditingController();
  bool _hasRequestedPermission = false;

  @override
  void initState() {
    super.initState();
    // Request notification permission when weather page loads (after login)
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _requestNotificationPermission();
    });
  }

  Future<void> _requestNotificationPermission() async {
    if (_hasRequestedPermission) return;
    _hasRequestedPermission = true;

    try {
      final messagingService = getIt<FirebaseMessagingService>();
      
      // Check current permission status
      final currentStatus = await messagingService.getPermissionStatus();
      
      // Only request if permission is not determined or denied
      if (currentStatus == AuthorizationStatus.notDetermined || 
          currentStatus == AuthorizationStatus.denied) {
        
        // Show a dialog explaining why we need permission
        final shouldRequest = await showDialog<bool>(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text('Enable Notifications'),
            content: const Text(
              'Stay updated with weather alerts and important notifications. Would you like to enable notifications?',
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.of(context).pop(false),
                child: const Text('Not Now'),
              ),
              TextButton(
                onPressed: () => Navigator.of(context).pop(true),
                child: const Text('Enable'),
              ),
            ],
          ),
        );

        if (shouldRequest == true && mounted) {
          // Request permission (shows system dialog)
          final result = await messagingService.requestPermission();
          
          if (mounted) {
            if (result.isGranted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Notifications enabled successfully!'),
                  backgroundColor: Colors.green,
                ),
              );
              // Get FCM token after permission granted
              await messagingService.getToken();
            } else if (result.isDenied) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Notification permission denied. You can enable it later in settings.'),
                  backgroundColor: Colors.orange,
                ),
              );
            }
          }
        }
      } else if (currentStatus == AuthorizationStatus.authorized) {
        // Permission already granted, get token
        await messagingService.getToken();
      }
    } catch (e) {
      debugPrint('Error requesting notification permission: $e');
    }
  }

  @override
  void dispose() {
    _searchController.dispose();
    _cityController.dispose();
    super.dispose();
  }

  void _addCity(String cityName) {
    if (cityName.trim().isEmpty) return;
    context.read<WeatherBloc>().add(
      FetchWeatherEvent(location: cityName.trim()),
    );
    _cityController.clear();
  }

  List<Autogenerated> _getCitiesFromState(WeatherState state) {
    return state.cities;
  }

  // Helper: Build address string from area data
  String _buildAddress(dynamic area) {
    final parts = <String>[];
    if (area.areaName?.isNotEmpty == true) {
      parts.add(area.areaName!.first.value ?? '');
    }
    if (area.region?.isNotEmpty == true) {
      parts.add(area.region!.first.value ?? '');
    }
    if (area.country?.isNotEmpty == true) {
      parts.add(area.country!.first.value ?? '');
    }
    return parts.isEmpty ? 'Current Location' : parts.join(', ');
  }

  Map<String, dynamic> _extractCurrentWeather(
    Autogenerated data,
    dynamic area,
  ) {
    final condition = data.currentCondition?.isNotEmpty == true
        ? data.currentCondition!.first
        : null;

    return {
      'address': _buildAddress(area),
      'temperature': condition?.tempC != null ? '${condition!.tempC}°C' : 'N/A',
      'humidity': condition?.humidity != null
          ? '${condition!.humidity}%'
          : 'N/A',
      'windSpeed': condition?.windspeedKmph != null
          ? '${condition!.windspeedKmph} km/h'
          : 'N/A',
      'weatherDesc': condition?.weatherDesc?.isNotEmpty == true
          ? condition!.weatherDesc!.first.value ?? 'N/A'
          : 'N/A',
      'feelsLike': condition?.feelsLikeC != null
          ? '${condition!.feelsLikeC}°C'
          : 'N/A',
      'pressure': condition?.pressure != null
          ? '${condition!.pressure} mb'
          : 'N/A',
      'uvIndex': condition?.uvIndex ?? 'N/A',
      'country': area.country?.isNotEmpty == true
          ? area.country!.first.value ?? ''
          : '',
      'region': area.region?.isNotEmpty == true
          ? area.region!.first.value ?? ''
          : '',
      'latitude': area.latitude ?? '',
      'longitude': area.longitude ?? '',
      'date': 'Today',
      'type': 'current',
    };
  }

  // Helper: Extract forecast weather data
  Map<String, dynamic> _extractForecastWeather(
    dynamic weather,
    String baseAddress,
    Autogenerated data,
  ) {
    final nearestArea = data.nearestArea?.isNotEmpty == true
        ? data.nearestArea!.first
        : null;

    return {
      'address': baseAddress.isNotEmpty ? baseAddress : 'Forecast',
      'temperature': weather.avgtempC != null ? '${weather.avgtempC}°C' : 'N/A',
      'humidity': 'N/A',
      'windSpeed': 'N/A',
      'weatherDesc': 'Forecast',
      'country': nearestArea?.country?.isNotEmpty == true
          ? nearestArea!.country!.first.value ?? ''
          : '',
      'region': nearestArea?.region?.isNotEmpty == true
          ? nearestArea!.region!.first.value ?? ''
          : '',
      'date': weather.date ?? 'N/A',
      'maxTemp': weather.maxtempC ?? 'N/A',
      'minTemp': weather.mintempC ?? 'N/A',
      'avgtempC': weather.avgtempC ?? 'N/A',
      'avgtempF': weather.avgtempF ?? 'N/A',
      'sunHour': weather.sunHour ?? 'N/A',
      'uvIndex': weather.uvIndex ?? 'N/A',
      'type': 'forecast',
    };
  }

  List<Map<String, dynamic>> _buildWeatherList(List<Autogenerated> citiesList) {
    final weatherList = <Map<String, dynamic>>[];

    for (var data in citiesList) {
      // Process current weather
      if (data.nearestArea?.isNotEmpty == true) {
        for (var area in data.nearestArea!) {
          weatherList.add(_extractCurrentWeather(data, area));
        }
      }

      // Process forecast weather
      if (data.weather?.isNotEmpty == true) {
        final baseAddress =
            data.nearestArea?.isNotEmpty == true &&
                data.nearestArea!.first.areaName?.isNotEmpty == true
            ? data.nearestArea!.first.areaName!.first.value ?? ''
            : '';
        for (var weather in data.weather!) {
          weatherList.add(_extractForecastWeather(weather, baseAddress, data));
        }
      }
    }

    return weatherList;
  }

  // Helper: Filter weather list based on search query
  List<Map<String, dynamic>> _filterWeatherList(
    List<Map<String, dynamic>> weatherList,
    String searchQuery,
  ) {
    if (searchQuery.isEmpty) return weatherList;

    final query = searchQuery.toLowerCase();
    return weatherList.where((item) {
      final address = (item['address'] ?? '').toString().toLowerCase();
      final country = (item['country'] ?? '').toString().toLowerCase();
      final region = (item['region'] ?? '').toString().toLowerCase();
      final date = (item['date'] ?? '').toString().toLowerCase();

      return address.contains(query) ||
          country.contains(query) ||
          region.contains(query) ||
          date.contains(query);
    }).toList();
  }

  // Helper: Get city name from data for refresh
  String? _getCityName(Autogenerated city) {
    if (city.nearestArea?.isNotEmpty == true) {
      final area = city.nearestArea!.first;
      if (area.areaName?.isNotEmpty == true) {
        return area.areaName!.first.value;
      }
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [Color(0xFF1E3C72), Color(0xFF2A5298), Color(0xFF7B68EE)],
          ),
        ),
        child: SafeArea(
          child: BlocBuilder<WeatherBloc, WeatherState>(
            builder: (context, state) {
              final citiesList = _getCitiesFromState(state);

              if (state is WeatherInitial && citiesList.isEmpty) {
                return _buildInitialEmptyState(context);
              }

              // Loading state
              if (state is WeatherLoading) {
                return Column(
                  children: [
                    _buildHeader(context, citiesList, state.searchQuery),
                    _buildSkeletonLoadingState(),
                  ],
                );
              }

              // Error state
              if (state is WeatherError) {
                return _buildErrorState(context, state.message);
              }

              // Empty state with message
              if (citiesList.isEmpty) {
                return _buildEmptyState();
              }

              // Main content with weather list
              final weatherList = _buildWeatherList(citiesList);
              final filteredList = _filterWeatherList(
                weatherList,
                state.searchQuery,
              );

              return Column(
                children: [
                  _buildHeader(context, citiesList, state.searchQuery),
                  _buildWeatherListWidget(filteredList, weatherList),
                ],
              );
            },
          ),
        ),
      ),
    );
  }

  Widget _buildInitialEmptyState(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.wb_sunny, size: 100, color: Colors.white),
          SizedBox(height: 30),
          Text(
            'Weather App',
            style: TextStyle(
              fontSize: 32,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          SizedBox(height: 10),
          Text(
            'Get weather information for any location',
            style: TextStyle(fontSize: 16, color: Colors.white70),
          ),
          SizedBox(height: 50),
          ElevatedButton.icon(
            onPressed: () =>
                context.read<WeatherBloc>().add(FetchWeatherEvent()),
            icon: Icon(Icons.cloud_download, size: 24),
            label: Text('Fetch Weather Status', style: TextStyle(fontSize: 18)),
            style: ElevatedButton.styleFrom(
              padding: EdgeInsets.symmetric(horizontal: 32, vertical: 16),
              backgroundColor: Colors.white,
              foregroundColor: Color(0xFF1E3C72),
              elevation: 8,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30),
              ),
            ),
          ),
        ],
      ),
    );
  }

  //  Loading state with Skeletonizer
  Widget _buildSkeletonLoadingState() {
    return Expanded(
      child: Skeletonizer(
        enabled: true,

        child: ListView.builder(
          itemCount: 3,
          padding: EdgeInsets.symmetric(horizontal: 20),
          physics: BouncingScrollPhysics(),
          itemBuilder: (context, index) {
            return _buildSkeletonWeatherCard();
          },
        ),
      ),
    );
  }

  Widget _buildSkeletonWeatherCard() {
    return Container(
      margin: EdgeInsets.only(bottom: 15),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Colors.white, Colors.blue.shade50],
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 15,
            offset: Offset(0, 5),
          ),
        ],
      ),
      child: Padding(
        padding: EdgeInsets.all(20),
        child: Row(
          children: [
            // Skeleton icon
            Container(
              width: 70,
              height: 70,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
                ),
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: Colors.blue.withOpacity(0.3),
                    blurRadius: 10,
                    offset: Offset(0, 5),
                  ),
                ],
              ),
              child: Icon(Icons.wb_sunny, color: Colors.white, size: 35),
            ),
            SizedBox(width: 20),
            // Skeleton location info
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Icon(Icons.location_on, color: Colors.red, size: 20),
                      SizedBox(width: 5),
                      Text(
                        'Loading Location...',
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF1E3C72),
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                  SizedBox(height: 5),
                  // Text('Loading...', style: TextStyle(fontSize: 14, color: Colors.grey[600])),
                  SizedBox(height: 8),
                  Container(
                    padding: EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: Color(0xFF667EEA).withOpacity(0.1),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    // child: Text(
                    //   'Loading...',
                    //   style: TextStyle(fontSize: 12, color: Color(0xFF667EEA), fontWeight: FontWeight.w500),
                    // ),
                  ),
                ],
              ),
            ),
            // Skeleton temperature info
            Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Text(
                  '0°C',
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFFFF6B6B),
                  ),
                ),
                SizedBox(height: 5),
                Row(
                  children: [
                    Icon(Icons.water_drop, size: 14, color: Colors.blue),
                    SizedBox(width: 4),
                    Text(
                      '0%',
                      style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                    ),
                  ],
                ),
                SizedBox(height: 3),
                Row(
                  children: [
                    Icon(Icons.air, size: 14, color: Colors.grey),
                    SizedBox(width: 4),
                    Text(
                      '0 km/h',
                      style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildErrorState(BuildContext context, String message) {
    return Center(
      child: Container(
        margin: EdgeInsets.all(30),
        padding: EdgeInsets.all(30),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(color: Colors.black.withOpacity(0.1), blurRadius: 15),
          ],
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.error_outline, size: 80, color: Colors.red),
            SizedBox(height: 20),
            Text(
              'Oops!',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: Color(0xFF1E3C72),
              ),
            ),
            SizedBox(height: 10),
            Text(
              message,
              style: TextStyle(fontSize: 16, color: Colors.grey[700]),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 30),
            ElevatedButton.icon(
              onPressed: () =>
                  context.read<WeatherBloc>().add(FetchWeatherEvent()),
              icon: Icon(Icons.refresh),
              label: Text('Retry'),
              style: ElevatedButton.styleFrom(
                padding: EdgeInsets.symmetric(horizontal: 30, vertical: 15),
                backgroundColor: Color(0xFF1E3C72),
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(25),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // UI Widget: Empty state
  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.wb_sunny, size: 100, color: Colors.white),
          SizedBox(height: 30),
          Text(
            'Weather App',
            style: TextStyle(
              fontSize: 32,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          SizedBox(height: 10),
          Text(
            'Add cities to see weather information',
            style: TextStyle(fontSize: 16, color: Colors.white70),
          ),
        ],
      ),
    );
  }

  // UI Widget: Header with search and add city
  Widget _buildHeader(
    BuildContext context,
    List<Autogenerated> citiesList,
    String searchQuery,
  ) {
    final weatherList = _buildWeatherList(citiesList);
    final filteredList = _filterWeatherList(weatherList, searchQuery);

    return Container(
      padding: EdgeInsets.all(20),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Weather',
                style: TextStyle(
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  color: Colors.white,
                ),
              ),
              Row(
                children: [
                  IconButton(
                    icon: Icon(Icons.refresh, color: Colors.white),
                    onPressed: () {
                      final cityName = citiesList.isNotEmpty
                          ? _getCityName(citiesList.first)
                          : null;
                      if (cityName != null) {
                        context.read<WeatherBloc>().add(
                          FetchWeatherEvent(location: cityName),
                        );
                      }
                    },
                  ),
                  IconButton(
                    icon: Icon(Icons.delete_outline, color: Colors.white),
                    onPressed: () =>
                        context.read<WeatherBloc>().add(ClearCitiesEvent()),
                    tooltip: 'Clear all cities',
                  ),
                  IconButton(
                    icon: Icon(Icons.logout, color: Colors.white),
                    onPressed: () {
                      context.read<AuthBloc>().add(SignOutRequested());
                    },
                    tooltip: 'Sign Out',
                  ),
                ],
              ),
            ],
          ),
          SizedBox(height: 15),
          _buildCityInputField(),
          SizedBox(height: 15),
          // _buildSearchField(context, searchQuery),
          SizedBox(height: 10),
          Text(
            '${citiesList.length} city${citiesList.length != 1 ? 'ies' : ''} • ${filteredList.length} location${filteredList.length != 1 ? 's' : ''} found',
            style: TextStyle(color: Colors.white70, fontSize: 14),
          ),
        ],
      ),
    );
  }

  // UI Widget: City input field
  Widget _buildCityInputField() {
    return Row(
      children: [
        Expanded(
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.2),
              borderRadius: BorderRadius.circular(25),
              border: Border.all(
                color: Colors.white.withOpacity(0.3),
                width: 1,
              ),
            ),
            child: TextField(
              controller: _cityController,
              style: TextStyle(color: Colors.white),
              decoration: InputDecoration(
                hintText: 'Enter city name (e.g., Amman, London, Paris)...',
                hintStyle: TextStyle(color: Colors.white70, fontSize: 13),
                prefixIcon: Icon(Icons.add_location, color: Colors.white),
                border: InputBorder.none,
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 15,
                ),
              ),
              onSubmitted: (value) => _addCity(value),
            ),
          ),
        ),
        SizedBox(width: 10),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            shape: BoxShape.circle,
          ),
          child: IconButton(
            icon: Icon(Icons.add, color: Color(0xFF1E3C72)),
            onPressed: () => _addCity(_cityController.text),
          ),
        ),
      ],
    );
  }

  // UI Widget: Search field
  // Widget _buildSearchField(BuildContext context, String searchQuery) {
  //   // Sync controller with BLoC state (without triggering onChanged)
  //   if (_searchController.text != searchQuery) {
  //     _searchController.value = TextEditingValue(
  //       text: searchQuery,
  //       selection: TextSelection.collapsed(offset: searchQuery.length),
  //     );
  //   }

  //   return Container(
  //     decoration: BoxDecoration(
  //       color: Colors.white.withOpacity(0.2),
  //       borderRadius: BorderRadius.circular(25),
  //       border: Border.all(color: Colors.white.withOpacity(0.3), width: 1),
  //     ),
  //     child: TextField(
  //       controller: _searchController,
  //       style: TextStyle(color: Colors.white),
  //       decoration: InputDecoration(
  //         hintText: 'Search by location or date...',
  //         hintStyle: TextStyle(color: Colors.white70),
  //         prefixIcon: Icon(Icons.search, color: Colors.white),
  //         suffixIcon: searchQuery.isNotEmpty
  //             ? IconButton(
  //                 icon: Icon(Icons.clear, color: Colors.white),
  //                 onPressed: () {
  //                   _searchController.clear();
  //                   context.read<WeatherBloc>().add(SearchQueryChangedEvent(''));
  //                 },
  //               )
  //             : null,
  //         border: InputBorder.none,
  //         contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 15),
  //       ),
  //       onChanged: (value) {
  //         // Only dispatch event on user input, not on programmatic changes
  //         if (value != searchQuery) {
  //           context.read<WeatherBloc>().add(SearchQueryChangedEvent(value));
  //         }
  //       },
  //     ),
  //   );
  // }

  // UI Widget: Weather list
  Widget _buildWeatherListWidget(
    List<Map<String, dynamic>> filteredList,
    List<Map<String, dynamic>> weatherList,
  ) {
    if (filteredList.isEmpty) {
      return Expanded(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.search_off, size: 80, color: Colors.white54),
              SizedBox(height: 20),
              Text(
                weatherList.isEmpty
                    ? 'No weather data available'
                    : 'No results found',
                style: TextStyle(fontSize: 18, color: Colors.white70),
              ),
            ],
          ),
        ),
      );
    }

    return Expanded(
      child: ListView.builder(
        itemCount: filteredList.length,
        padding: EdgeInsets.symmetric(horizontal: 20),
        physics: BouncingScrollPhysics(),
        itemBuilder: (context, index) {
          final item = filteredList[index];
          final isCurrent = item['type'] == 'current';

          return TweenAnimationBuilder<double>(
            tween: Tween(begin: 0.0, end: 1.0),
            duration: Duration(milliseconds: 300 + (index * 100)),
            builder: (context, value, child) {
              return Opacity(
                opacity: value,
                child: Transform.translate(
                  offset: Offset(0, 20 * (1 - value)),
                  child: child,
                ),
              );
            },
            child: _buildWeatherCard(item, isCurrent),
          );
        },
      ),
    );
  }

  // UI Widget: Weather card item
  Widget _buildWeatherCard(Map<String, dynamic> item, bool isCurrent) {
    return Container(
      margin: EdgeInsets.only(bottom: 15),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: isCurrent
              ? [Colors.white, Colors.blue.shade50]
              : [
                  Colors.white.withOpacity(0.95),
                  Colors.white.withOpacity(0.85),
                ],
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 15,
            offset: Offset(0, 5),
          ),
        ],
      ),
      child: Padding(
        padding: EdgeInsets.all(20),
        child: Row(
          children: [
            _buildWeatherIcon(isCurrent),
            SizedBox(width: 20),
            Expanded(child: _buildLocationInfo(item, isCurrent)),
            _buildTemperatureInfo(item, isCurrent),
          ],
        ),
      ),
    );
  }

  // UI Widget: Weather icon
  Widget _buildWeatherIcon(bool isCurrent) {
    return Container(
      width: 70,
      height: 70,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
        ),
        shape: BoxShape.circle,
        boxShadow: [
          BoxShadow(
            color: Colors.blue.withOpacity(0.3),
            blurRadius: 10,
            offset: Offset(0, 5),
          ),
        ],
      ),
      child: Icon(
        isCurrent ? Icons.wb_sunny : Icons.calendar_today,
        color: Colors.white,
        size: 35,
      ),
    );
  }

  // UI Widget: Location info
  Widget _buildLocationInfo(Map<String, dynamic> item, bool isCurrent) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(Icons.location_on, color: Colors.red, size: 20),
            SizedBox(width: 5),
            Expanded(
              child: Text(
                item['address'] ?? 'Unknown',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF1E3C72),
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
        if (item['date'] != null) ...[
          SizedBox(height: 5),
          Text(
            item['date'] ?? '',
            style: TextStyle(fontSize: 14, color: Colors.grey[600]),
          ),
        ],
        if (isCurrent && item['weatherDesc'] != null) ...[
          SizedBox(height: 8),
          Container(
            padding: EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: Color(0xFF667EEA).withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              item['weatherDesc'] ?? '',
              style: TextStyle(
                fontSize: 12,
                color: Color(0xFF667EEA),
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
        ],
      ],
    );
  }

  // UI Widget: Temperature info
  Widget _buildTemperatureInfo(Map<String, dynamic> item, bool isCurrent) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        Text(
          item['temperature'] ?? 'N/A',
          style: TextStyle(
            fontSize: 28,
            fontWeight: FontWeight.bold,
            color: Color(0xFFFF6B6B),
          ),
        ),
        if (isCurrent) ...[
          SizedBox(height: 5),
          _buildInfoRow(
            Icons.water_drop,
            item['humidity'] ?? 'N/A',
            Colors.blue,
          ),
          SizedBox(height: 3),
          _buildInfoRow(Icons.air, item['windSpeed'] ?? 'N/A', Colors.grey),
          if (item['feelsLike'] != null && item['feelsLike'] != 'N/A') ...[
            SizedBox(height: 3),
            _buildInfoRow(
              Icons.thermostat,
              'Feels: ${item['feelsLike']}',
              Colors.orange,
            ),
          ],
        ] else ...[
          SizedBox(height: 5),
          Text(
            'Max: ${item['maxTemp']}°C',
            style: TextStyle(
              fontSize: 12,
              color: Colors.orange,
              fontWeight: FontWeight.w600,
            ),
          ),
          Text(
            'Min: ${item['minTemp']}°C',
            style: TextStyle(
              fontSize: 12,
              color: Colors.blue,
              fontWeight: FontWeight.w600,
            ),
          ),
          if (item['uvIndex'] != null && item['uvIndex'] != 'N/A')
            Padding(
              padding: EdgeInsets.only(top: 3),
              child: Text(
                'UV: ${item['uvIndex']}',
                style: TextStyle(
                  fontSize: 11,
                  color: Colors.purple,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
        ],
      ],
    );
  }

  // UI Widget: Info row helper
  Widget _buildInfoRow(IconData icon, String text, Color color) {
    return Row(
      children: [
        Icon(icon, size: 14, color: color),
        SizedBox(width: 4),
        Text(text, style: TextStyle(fontSize: 12, color: Colors.grey[600])),
      ],
    );
  }
}