import 'package:flutterweather/features/data/model/autogenerated.dart';

abstract class WeatherState {
  final List<Autogenerated> cities;
  final String searchQuery;
  final Map<int, bool> hoverStates;

  WeatherState({
    this.cities = const [],
    this.searchQuery = '',
    this.hoverStates = const {},
  });
}

class WeatherInitial extends WeatherState {
  WeatherInitial({super.cities, super.searchQuery, super.hoverStates});
}

class WeatherLoading extends WeatherState {
  WeatherLoading({super.cities, super.searchQuery, super.hoverStates});
}

class WeatherLoaded extends WeatherState {
  final Autogenerated data;

  WeatherLoaded(
    this.data, {
    super.cities,
    super.searchQuery,
    super.hoverStates,
  });
}

class WeatherError extends WeatherState {
  final String message;

  WeatherError(
    this.message, {
    super.cities,
    super.searchQuery,
    super.hoverStates,
  });
}
