


import 'package:flutterweather/features/data/model/autogenerated.dart';

abstract class WeatherState {
  final List<Autogenerated> cities;
  final String searchQuery;

  WeatherState({this.cities = const [], this.searchQuery = ''});
}

class WeatherInitial extends WeatherState {
  WeatherInitial({super.cities, super.searchQuery});
}

class WeatherLoading extends WeatherState {
  WeatherLoading({super.cities, super.searchQuery});
}

class WeatherLoaded extends WeatherState {
  final Autogenerated data;
  
  WeatherLoaded(this.data, {super.cities, super.searchQuery});
}

class WeatherError extends WeatherState {
  final String message;
  
  WeatherError(this.message, {super.cities, super.searchQuery});
}

